name: Update Hosts

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  update_hosts:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install requests

      - name: Set git config
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@github.com"

      - name: Run updater
        run: |
          python upd_hosts.py

      - name: Commit and push changes
        run: |
          git add hosts.txt
          git commit -am "Update hosts file"
          git push

      - name: Cleanup old workflow runs
        run: |
          api_response=$(curl -s -X GET \
            -H "Authorization: token ${{ secrets.PAT_TOKEN }}" \
            "https://api.github.com/repos/${{ github.repository }}/actions/runs")

          # Check if the response contains valid data
          if [ "$(echo "$api_response" | jq '.workflow_runs')" != "null" ]; then
            runsToDelete=$(echo "$api_response" | jq -r '.workflow_runs | sort_by(.created_at) | .[:-5] | .[] | .id')

            for runId in $runsToDelete; do
              curl -s -X DELETE \
                -H "Authorization: token ${{ secrets.PAT_TOKEN }}" \
                "https://api.github.com/repos/${{ github.repository }}/actions/runs/$runId"
            done
          else
            echo "No workflow runs to delete."
          fi
